/* eslint-disable */
const countryCodes = [
  "AD",
  "AE",
  "AF",
  "AG",
  "AI",
  "AL",
  "AM",
  "AO",
  "AQ",
  "AR",
  "AS",
  "AT",
  "AU",
  "AW",
  "AX",
  "AZ",
  "BA",
  "BB",
  "BD",
  "BE",
  "BF",
  "BG",
  "BH",
  "BI",
  "BJ",
  "BL",
  "BM",
  "BN",
  "BO",
  "BQ",
  "BR",
  "BS",
  "BT",
  "BV",
  "BW",
  "BY",
  "BZ",
  "CA",
  "CC",
  "CD",
  "CF",
  "CG",
  "CH",
  "CI",
  "CK",
  "CL",
  "CM",
  "CN",
  "CO",
  "CR",
  "CU",
  "CV",
  "CW",
  "CX",
  "CY",
  "CZ",
  "DE",
  "DJ",
  "DK",
  "DM",
  "DO",
  "DZ",
  "EC",
  "EE",
  "EG",
  "EH",
  "ER",
  "ES",
  "ET",
  "FI",
  "FJ",
  "FK",
  "FM",
  "FO",
  "FR",
  "GA",
  "GB",
  "GD",
  "GE",
  "GF",
  "GG",
  "GH",
  "GI",
  "GL",
  "GM",
  "GN",
  "GP",
  "GQ",
  "GR",
  "GS",
  "GT",
  "GU",
  "GW",
  "GY",
  "HK",
  "HM",
  "HN",
  "HR",
  "HT",
  "HU",
  "ID",
  "IE",
  "IL",
  "IM",
  "IN",
  "IO",
  "IQ",
  "IR",
  "IS",
  "IT",
  "JE",
  "JM",
  "JO",
  "JP",
  "KE",
  "KG",
  "KH",
  "KI",
  "KM",
  "KN",
  "KP",
  "KR",
  "KW",
  "KY",
  "KZ",
  "LA",
  "LB",
  "LC",
  "LI",
  "LK",
  "LR",
  "LS",
  "LT",
  "LU",
  "LV",
  "LY",
  "MA",
  "MC",
  "MD",
  "ME",
  "MF",
  "MG",
  "MH",
  "MK",
  "ML",
  "MM",
  "MN",
  "MO",
  "MP",
  "MQ",
  "MR",
  "MS",
  "MT",
  "MU",
  "MV",
  "MW",
  "MX",
  "MY",
  "MZ",
  "NA",
  "NC",
  "NE",
  "NF",
  "NG",
  "NI",
  "NL",
  "NO",
  "NP",
  "NR",
  "NU",
  "NZ",
  "OM",
  "PA",
  "PE",
  "PF",
  "PG",
  "PH",
  "PK",
  "PL",
  "PM",
  "PN",
  "PR",
  "PS",
  "PT",
  "PW",
  "PY",
  "QA",
  "RE",
  "RO",
  "RS",
  "RU",
  "RW",
  "SA",
  "SB",
  "SC",
  "SD",
  "SE",
  "SG",
  "SH",
  "SI",
  "SJ",
  "SK",
  "SL",
  "SM",
  "SN",
  "SO",
  "SR",
  "SS",
  "ST",
  "SV",
  "SX",
  "SY",
  "SZ",
  "TC",
  "TD",
  "TF",
  "TG",
  "TH",
  "TJ",
  "TK",
  "TL",
  "TM",
  "TN",
  "TO",
  "TR",
  "TT",
  "TV",
  "TW",
  "TZ",
  "UA",
  "UG",
  "UM",
  "US",
  "UY",
  "UZ",
  "VA",
  "VC",
  "VE",
  "VG",
  "VI",
  "VN",
  "VU",
  "WF",
  "WS",
  "YE",
  "YT",
  "ZA",
  "ZM",
  "ZW",
];

// change this mapping if you need to change the behavior how languages are recognized
const countryMapping = {
  AE: { locale: "ar-ae" },
  AL: { locale: "sq-al" },
  AR: { locale: "es-419" },
  AT: { locale: "de-de" },
  AU: { locale: "en-us" },
  BE: { locale: "fr-fr" },
  BG: { locale: "bg-bg" },
  BH: { locale: "ar-bh" },
  BO: { locale: "es-419" },
  BR: { locale: "pt-br" },
  BY: { locale: "be-by" },
  CA: { locale: "en-us" },
  CH: { locale: "de-de" },
  CL: { locale: "es-419" },
  CN: { locale: "zh-cn" },
  CO: { locale: "es-419" },
  CR: { locale: "es-419" },
  CY: { locale: "el-cy" },
  CZ: { locale: "cs-cz" },
  DE: { locale: "de-de" },
  DK: { locale: "da-dk" },
  DO: { locale: "es-419" },
  DZ: { locale: "ar-dz" },
  EC: { locale: "es-419" },
  EE: { locale: "et-ee" },
  EG: { locale: "ar-eg" },
  ES: { locale: "es-419" },
  FI: { locale: "fi-fi" },
  FR: { locale: "fr-fr" },
  GR: { locale: "el-gr" },
  GT: { locale: "es-419" },
  HK: { locale: "zh-hk" },
  HN: { locale: "es-419" },
  HR: { locale: "hr-hr" },
  HU: { locale: "hu-hu" },
  ID: { locale: "in-id" },
  IE: { locale: "ga-ie" },
  IL: { locale: "iw-il" },
  IN: { locale: "hi-in" },
  IQ: { locale: "ar-iq" },
  IS: { locale: "is-is" },
  IT: { locale: "it-it" },
  JO: { locale: "ar-jo" },
  JP: { locale: "ja-jp" },
  KW: { locale: "ar-kw" },
  LB: { locale: "ar-lb" },
  LT: { locale: "lt-lt" },
  LU: { locale: "fr-fr" },
  LV: { locale: "lv-lv" },
  MA: { locale: "ar-ma" },
  MT: { locale: "en-us" },
  MX: { locale: "es-419" },
  MY: { locale: "ms-my" },
  NI: { locale: "es-419" },
  NL: { locale: "nl-nl" },
  NO: { locale: "no-no" },
  NZ: { locale: "en-us" },
  OM: { locale: "ar-om" },
  PA: { locale: "es-419" },
  PE: { locale: "es-419" },
  PH: { locale: "en-us" },
  PL: { locale: "pl-pl" },
  PR: { locale: "es-419" },
  PT: { locale: "pt-pt" },
  PY: { locale: "es-419" },
  QA: { locale: "ar-qa" },
  RO: { locale: "ro-ro" },
  SA: { locale: "ar-sa" },
  SD: { locale: "ar-sd" },
  SE: { locale: "sv-se" },
  SG: { locale: "zh-sg" },
  SI: { locale: "sl-si" },
  SV: { locale: "es-419" },
  TH: { locale: "th-th" },
  TN: { locale: "ar-tn" },
  TR: { locale: "tr-tr" },
  UA: { locale: "uk-ua" },
  UK: { locale: "en-us" },
  US: { locale: "en-us" },
  UY: { locale: "es-419" },
  VE: { locale: "es-419" },
  YE: { locale: "ar-ye" },
  ZA: { locale: "en-us" },
};

export { countryCodes, countryMapping };
